### ISSUE TITLE
Cannot use CloudShell if I enable Favicon.

### ISSUE THREAD

**Issue by Jennas-Lee** [nalbam/aws-navbar-extension#3]
Hello. I'm using this extension very well. Thank you for the development.

If I disable 'Favicon' option, I can use CloudShell like this:

![image](https://user-images.githubusercontent.com/55793046/186891164-7fd7359c-4f02-4d72-b2be-cbed546bbc05.png)

If I use 'Favicon' option, I cannot use CloudShell like this:

![image](https://user-images.githubusercontent.com/55793046/186891251-8cad38f5-7dba-4842-84fd-cf2a9369c215.png)

I think some code in CloudShell uses the DOM of icon based on id. Because original icon has a id like this:

![image](https://user-images.githubusercontent.com/55793046/186892291-c86c165c-d8e7-474c-86dd-87d43e9cb685.png)

``` html
<link href="data:image/png;base64,iVBORw0KGg..." type="image/ico" rel="icon" id="icon">
<link href="data:image/png;base64,iVBORw0KGg..." type="image/ico" rel="shortcut icon" id="shortcutIcon">
```

**Comment by nalbam** [comment]
Thank you.
Your PR has been merged and version 1.5.5 has been released.

https://github.com/nalbam/aws-navbar-extension/pull/4

https://github.com/nalbam/aws-navbar-extension/releases/tag/1.5.5
